# ASSIGNMENT : IRIS MULTI-CLASS CLASSIFICATION

###### Purpose :
To predict the species of flower .
###### Description :
The dataset contains a set of 150 records under 5 attributes - Petal Length, Petal Width, Sepal Length, Sepal width and Class(Species).
###### Requirements :
1) Code must be in tf 2.0 .

2) Accuracy must be in between 95-97% .

3) Model shouldn't be Overfit (You can add drop out layer for this) .

### STEP 1 : Load all the necessary libraries 

In [1]:
from tensorflow import keras
import numpy as np
import pandas as pd
import sklearn

### STEP 2 : Data Preparation
This step consists of multiple sub steps from data loading [download](https://github.com/ramsha275/PIAIC-Sir-Anees-Quarter-2/blob/master/Deep%20Learning/iris.csv),shuffling ,spliting in **Train** and **Test** sets to one-hot-enconding on labels . 


In [2]:
df1 = pd.read_csv('CSV/iris.csv')

In [3]:
df = df1.copy(deep=True)
df.replace(df["variety"].unique(), [0,1,2], inplace=True)

In [4]:
df = sklearn.utils.shuffle(df)
Train_Dataset = np.array(df[:112].drop(["variety"],axis=1))
Train_Labels = np.array(df[:112]["variety"])
Test_Dataset = np.array(df[112:].drop(["variety"],axis=1))
Test_Labels = np.array(df[112:]["variety"])

In [5]:
Train_Labels = keras.utils.to_categorical(Train_Labels)
Test_Labels = keras.utils.to_categorical(Test_Labels)
print("Train_Features :",Train_Dataset.shape)
print("Train_Labels :",Train_Labels.shape)
print("Test_Features :",Test_Dataset.shape)
print("Test_Labels :",Test_Labels.shape)

Train_Features : (112, 4)
Train_Labels : (112, 3)
Test_Features : (38, 4)
Test_Labels : (38, 3)


### STEP 3 : Model Architecture 


###### Input : 4 
###### 1 hidden Layer : 8 nodes
###### Output : 3

In [6]:
model = keras.models.Sequential([
  keras.layers.Dense(128, activation='relu', input_shape=(4,)),
  keras.layers.Dense(3, activation='softmax')
])

### STEP 4 : Compilation Step 

In [7]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(Test_Dataset, Test_Labels, epochs=100)

Train on 38 samples
Epoch 1/100
38/38 [==============================] - 1s 32ms/sample - loss: 1.6231 - accuracy: 0.2368
Epoch 2/100
38/38 [==============================] - 0s 316us/sample - loss: 1.4105 - accuracy: 0.2368
Epoch 3/100
38/38 [==============================] - 0s 316us/sample - loss: 1.2451 - accuracy: 0.2368
Epoch 4/100
38/38 [==============================] - 0s 316us/sample - loss: 1.1154 - accuracy: 0.3158
Epoch 5/100
38/38 [==============================] - 0s 210us/sample - loss: 1.0394 - accuracy: 0.4737
Epoch 6/100
38/38 [==============================] - 0s 316us/sample - loss: 0.9909 - accuracy: 0.4737
Epoch 7/100
38/38 [==============================] - 0s 316us/sample - loss: 0.9619 - accuracy: 0.5789
Epoch 8/100
38/38 [==============================] - 0s 210us/sample - loss: 0.9502 - accuracy: 0.6316
Epoch 9/100
38/38 [==============================] - 0s 210us/sample - loss: 0.9409 - accuracy: 0.6579
Epoch 10/100
38/38 [==============================] - 

38/38 [==============================] - 0s 210us/sample - loss: 0.4438 - accuracy: 0.9474
Epoch 80/100
38/38 [==============================] - 0s 316us/sample - loss: 0.4407 - accuracy: 0.9474
Epoch 81/100
38/38 [==============================] - 0s 210us/sample - loss: 0.4361 - accuracy: 0.9737
Epoch 82/100
38/38 [==============================] - 0s 210us/sample - loss: 0.4374 - accuracy: 0.9737
Epoch 83/100
38/38 [==============================] - 0s 421us/sample - loss: 0.4361 - accuracy: 0.9737
Epoch 84/100
38/38 [==============================] - 0s 316us/sample - loss: 0.4332 - accuracy: 0.9737
Epoch 85/100
38/38 [==============================] - 0s 316us/sample - loss: 0.4285 - accuracy: 0.9737
Epoch 86/100
38/38 [==============================] - 0s 316us/sample - loss: 0.4251 - accuracy: 0.9737
Epoch 87/100
38/38 [==============================] - 0s 316us/sample - loss: 0.4219 - accuracy: 0.9737
Epoch 88/100
38/38 [==============================] - 0s 210us/sample - loss:

### STEP 5 : Evaluation 

In [8]:
model.save('best.h5') 

evaluation = model.evaluate(Test_Dataset,  Test_Labels, verbose=2)

38/1 - 0s - loss: 0.3738 - accuracy: 0.9737


### STEP 6 : Prediction 

In [9]:
print(f'2 = Virginica\n1 = Versicolor\n0 = Setosa')

print(f'Total Test_Dataset {len(Test_Labels)}')

for x in range(len(Test_Labels)):
    print("\nReal Value :",Test_Labels[x])
    print("Value Predicted :",model.predict_classes(Test_Dataset[[x]]))

2 = Virginica
1 = Versicolor
0 = Setosa
Total Test_Dataset 38

Real Value : [0. 1. 0.]
Value Predicted : [1]

Real Value : [1. 0. 0.]
Value Predicted : [0]

Real Value : [0. 0. 1.]
Value Predicted : [2]

Real Value : [0. 1. 0.]
Value Predicted : [1]

Real Value : [0. 1. 0.]
Value Predicted : [1]

Real Value : [0. 0. 1.]
Value Predicted : [2]

Real Value : [0. 0. 1.]
Value Predicted : [2]

Real Value : [0. 1. 0.]
Value Predicted : [1]

Real Value : [0. 0. 1.]
Value Predicted : [2]

Real Value : [1. 0. 0.]
Value Predicted : [0]

Real Value : [0. 1. 0.]
Value Predicted : [1]

Real Value : [0. 0. 1.]
Value Predicted : [2]

Real Value : [0. 1. 0.]
Value Predicted : [1]

Real Value : [0. 1. 0.]
Value Predicted : [1]

Real Value : [0. 1. 0.]
Value Predicted : [2]

Real Value : [1. 0. 0.]
Value Predicted : [0]

Real Value : [0. 0. 1.]
Value Predicted : [2]

Real Value : [0. 0. 1.]
Value Predicted : [2]

Real Value : [1. 0. 0.]
Value Predicted : [0]

Real Value : [1. 0. 0.]
Value Predicted : [0

In [10]:
print(Test_Labels)

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [11]:
print(Train_Labels)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1.