# ASSIGNMENT : IRIS MULTI-CLASS CLASSIFICATION

###### Purpose :
To predict the species of flower .
###### Description :
The dataset contains a set of 150 records under 5 attributes - Petal Length, Petal Width, Sepal Length, Sepal width and Class(Species).
###### Requirements :
1) Code must be in tf 2.0 .

2) Accuracy must be in between 95-97% .

3) Model shouldn't be Overfit (You can add drop out layer for this) .

### STEP 1 : Load all the necessary libraries 

In [1]:
from tensorflow import keras
import numpy as np
import pandas as pd
import sklearn

### STEP 2 : Data Preparation
This step consists of multiple sub steps from data loading [download](https://github.com/ramsha275/PIAIC-Sir-Anees-Quarter-2/blob/master/Deep%20Learning/iris.csv),shuffling ,spliting in **Train** and **Test** sets to one-hot-enconding on labels . 


In [2]:
df1 = pd.read_csv('CSV/iris.csv')

In [3]:
df = df1.copy(deep=True)
df.replace(df["variety"].unique(), [0,1,2], inplace=True)

In [4]:
df = sklearn.utils.shuffle(df)
Train_Dataset = np.array(df[:112].drop(["variety"],axis=1))
Train_Labels = np.array(df[:112]["variety"])
Test_Dataset = np.array(df[112:].drop(["variety"],axis=1))
Test_Labels = np.array(df[112:]["variety"])

In [5]:
Train_Labels = keras.utils.to_categorical(Train_Labels)
Test_Labels = keras.utils.to_categorical(Test_Labels)

### STEP 3 : Model Architecture 


###### Input : 4 
###### 1 hidden Layer : 8 nodes
###### Output : 3

In [6]:
model = keras.models.Sequential([
  keras.layers.Dense(128, activation='relu', input_shape=(4,)),
  keras.layers.Dense(3, activation='softmax')
])

### STEP 4 : Compilation Step 

In [7]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(Test_Dataset, Test_Labels, epochs=25, verbose=0)

### STEP 5 : Evaluation 

In [8]:
evaluation = model.evaluate(Test_Dataset,  Test_Labels, verbose=2)

38/1 - 0s - loss: 0.5725 - accuracy: 0.9737


### STEP 6 : Prediction 

In [9]:
print(f'Values: \n0 = Setosa\n1 = Versicolor\n2 = Virginica')

print('\nOne Hot Encoding:\n\t[1. 0. 0.] = Setosa')
print('\t[0. 1. 0.] = Versicolor')
print('\t[0. 0. 1.] = Virginica')


print(f'\nTotal Test_Dataset: {len(Test_Labels)}')

for x in range(len(Test_Labels)):
    print("\nReal Value :",Test_Labels[x])
    print("Value Predicted :",model.predict_classes(Test_Dataset[[x]]))

Values: 
0 = Setosa
1 = Versicolor
2 = Virginica

One Hot Encoding:
	[1. 0. 0.] = Setosa
	[0. 1. 0.] = Versicolor
	[0. 0. 1.] = Virginica

Total Test_Dataset: 38

Real Value : [0. 1. 0.]
Value Predicted : [1]

Real Value : [0. 0. 1.]
Value Predicted : [2]

Real Value : [1. 0. 0.]
Value Predicted : [0]

Real Value : [0. 1. 0.]
Value Predicted : [1]

Real Value : [0. 1. 0.]
Value Predicted : [1]

Real Value : [1. 0. 0.]
Value Predicted : [0]

Real Value : [0. 0. 1.]
Value Predicted : [2]

Real Value : [0. 0. 1.]
Value Predicted : [1]

Real Value : [0. 0. 1.]
Value Predicted : [2]

Real Value : [1. 0. 0.]
Value Predicted : [0]

Real Value : [1. 0. 0.]
Value Predicted : [0]

Real Value : [1. 0. 0.]
Value Predicted : [0]

Real Value : [1. 0. 0.]
Value Predicted : [0]

Real Value : [1. 0. 0.]
Value Predicted : [0]

Real Value : [1. 0. 0.]
Value Predicted : [0]

Real Value : [1. 0. 0.]
Value Predicted : [0]

Real Value : [0. 1. 0.]
Value Predicted : [1]

Real Value : [0. 0. 1.]
Value Predicte

In [10]:
model.save('Model.h5')